#!/bin/sh /etc/rc.common
# fubotv-monitor -- 周期上报守护进程的 procd 包装

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/ucode
SCRIPT=/usr/share/fubotv/report.uc
STATUS_FILE=/var/run/fubotv.status

start_service() {
	config_load fubotv

	local enabled
	config_get_bool enabled main enabled 0

	[ "$enabled" -eq 1 ] || {
		logger -t fubotv "service not started: fubotv.main.enabled=0"
		return 0
	}

	rm -f "$STATUS_FILE"

	procd_open_instance
	procd_set_param command "$PROG" "$SCRIPT"
	procd_set_param respawn 3600 5 5
	procd_set_param stderr 1
	procd_set_param file /etc/config/fubotv
	procd_close_instance
}

stop_service() {
	rm -f "$STATUS_FILE"
}

service_triggers() {
	procd_add_reload_trigger fubotv
}

reload_service() {
	stop
	start
}
